### ISSUE TITLE
FW: Some bugs in using Wire library

### ISSUE THREAD

**Issue by reloxx13** [Seeed-Studio/Mutichannel_Gas_Sensor#18]
Heya,

someone found some usage bugs of the wire library

> File "Sonoff-Tasmota/lib/Mutichannel_Gas_Sensor/src/MutichannelGasSensor.cpp", function "readData()" has a timeout, but there is no need to wait for something after a Wire.requestFrom().

Credits @Koepel
https://github.com/arendst/Sonoff-Tasmota/issues/2442

**Comment by Koepel** [comment]
This part in "readData()" can be removed:
```
while(Wire.available() == 0)
{
  if(timeout++ > 100)
    return -2;//time out
  delay(2);
}
```
There is no timeout with Wire.requestFrom().

This part is correct:
```
if(Wire.available() != 4)
  return -3;//rtnData length wrong
```
Testing if the same amount of data is received as is requested will capture all possible errors that the Wire library can detect.
