### ISSUE TITLE
Problems to use Multichannel_Gas_Sensor with Feather MO

### ISSUE THREAD

**Issue by Birthon** [Seeed-Studio/Mutichannel_Gas_Sensor#24]
Dear all,
I am trying to use Multichannel Gas Sensor with Feather MO without success. I have used the same code used in Arduino Mega that worked very well. When I try to use with Feather I get the following message: Error compiling for board Feather MO.

Thanks for any help,

Cesar

**Comment by OilSlick** [comment]
I have compiled it for a feather MO. One problem I ran into was [Serial vs SerialUSB](https://learn.adafruit.com/adafruit-feather-m0-bluefruit-le/adapting-sketches-to-m0).
