### ISSUE TITLE
Sensor seems able to read NO2 value only

### ISSUE THREAD

**Issue by aldoagosta** [Seeed-Studio/Mutichannel_Gas_Sensor#4]
Hi,

it seems that sensor (Grove version of MiCS-6814) does not read concentrations other than NO2.
NO2 is the only value changing over time while NH3 stands still even with a bottle of Ammonia placed below. By the way putting the ammonia bottle beside the sensor NO2 level decrease while NH3 stands still as said above and this seems to be coherent with manufacturer instructions here:
https://www.cdiweb.com/datasheets/e2v/AN172_Useandperform.pdf
Depending on the kind of gas the resistance goes higher of lower. So with NH3 the NO2 goes down but the strange thing is that NH3 value stands still. 
Therefore the variance in resistance should not update NO2 Value but instead it should change the other gases depending on the variance range. 

See the doc hereafterwhere the sensor manufacturer specifies how to calculate values from sensor (does not matter if the models listed are different): 
https://www.cdiweb.com/datasheets/e2v/Load%20resistance%20for%20MiCS%20sensors%20measurements.pdf

Moreover, also empierre found identical values and we live in different countries:
https://github.com/empierre/arduino/issues/15#issuecomment-189833091

The sensor is connected to a I2C port on arduino one Rev. 3 board thru Base Shield 2.

Thank you for support.
Regards

Aldo

**Comment by empierre** [comment]
I am waiting too for an answer or is this sensor crap ?

**Comment by ghost** [comment]
There're 3 independent channel for the sensor MiCS-6814, RED sensor, OX sensor as well as NH3 sensor. 
Please refer to this [datasheet](https://raw.githubusercontent.com/SeeedDocument/Grove-Multichannel_Gas_Sensor/master/res/MiCS-6814_Datasheet.pdf). 
Thanks.
