### ISSUE TITLE
Only NO2 channel seems to work

### ISSUE THREAD

**Issue by ericltongfb** [Seeed-Studio/Mutichannel_Gas_Sensor#6]
After doing testing with various gases and various environments, I usually get this output:

The concentration of NH3 is 0.99 ppm
The concentration of CO is 1.20 ppm
The concentration of NO2 is 1.18 ppm
The concentration of C3H8 is 1000.04 ppm
The concentration of C4H10 is 999.98 ppm
The concentration of CH4 is 2991.14 ppm
The concentration of H2 is 1.09 ppm
The concentration of C2H5OH is 1.40 ppm

It seems that other than the NO2 output, the rest of the output stays as the default values and does not vary with increase or decrease of concentration of those gases.  Is this a hardware issue or a firmware issue?

**Comment by empierre** [comment]
No answer but only close ?

**Comment by ghost** [comment]
Hello, sorry just made a mistake to close all of the issue of this library.
Please try calibrate the sensor in the fresh air again.
Are you sure the are around you contains the gas that didn't active?
Thanks.
